#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s
#
#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'spring-apps'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['spring-app1:8080', 'spring-app2:8080', 'spring-app3:8080']
#
#  - job_name: 'mysql'
#    static_configs:
#      - targets: ['mysql-exporter:9104']
#
#  - job_name: 'k6-metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['k6-exporter:9091']